### ISSUE TITLE
Where is load.bash?

### ISSUE THREAD

**Issue by kevinburkesegment** [buildkite-plugins/buildkite-plugin-tester#43]
I would like to run bats outside of Docker, which I find to be finicky and can never remember the start commands, but it's not clear where to find load.bash.

**Comment by toolmantim** [comment]
Hey @kevinburkesegment 👋🏼 This repo mainly exists of a Dockerfile — so it's a bit tricky to use it without Docker. `load.bash` is just some sugar for loading bats-assert, bats-mock, etc.

But if you install bats locally (https://bats-core.readthedocs.io) there's no reason you can't just it, but if you want to use bats-assert etc you'll need to download them locally too, and `load` each one

**Comment by kevinburkesegment** [comment]
Just FYI I only filed this ticket after installing bats-core (`brew install bats-core`) and looking for load.bash and not being able to find it.

**Comment by toolmantim** [comment]
Ah, load.bash is just a helper that loads bats-support, bats-assert, bats-mock and bats-file. It's not required to use those, but they're pretty handy!

If you want a purely local bats setup, installing from homebrew like you said is the way to go, and then following these insurrections to install each of the helper libraries (if you need): https://bats-core.readthedocs.io/en/stable/tutorial.html?highlight=Submodule#quick-installation

And then at the top of each test, instead of worrying about `load.bash`, you can use:

```sh
setup() {
  load 'test_helper/bats-support/load'
  load 'test_helper/bats-assert/load'
}
```

Let me know if that works for you! Or if you've any other questions.
